version: "3"

services:
  patzilla:
    build: .
    command: pserve /etc/patzilla.ini
    ports:
      - 6543:6543
    volumes:
      - ./patzilla.ini:/etc/patzilla.ini:ro
    networks:
      - patzilla_net
    container_name: patzilla
    depends_on:
      - mongodb
    restart: unless-stopped
  mongodb:
    image: mongo:4-focal
    ports:
      - 27017:27017
    networks:
      - patzilla_net
    container_name: mongodb
    restart: unless-stopped

networks:
  patzilla_net:
