version: "3"

services:
  patzilla:
    build: .
    image: aghster/patzilla
    ports:
      - 6543:6543
    volumes:
      - ./patzilla.ini:/patzilla.ini:ro
    networks:
      - patzilla_net
    container_name: patzilla
    depends_on:
      - mongodb
    restart: unless-stopped
  mongodb:
    image: mvertes/alpine-mongo
    ports:
      - 27017:27017
    networks:
      - patzilla_net
    container_name: mongodb
    restart: unless-stopped

networks:
  patzilla_net:
