name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:

  tests-backend:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [
          'ubuntu-latest',

          # Don't use macOS for now, it is currently unstable, otherwise slow. -- 2022-04-19, amo
          # 'macos-latest',
        ]
        python-version: ['2.7']

    defaults:
      run:
        shell: bash

    env:
      OPS_API_CONSUMER_KEY: ${{ secrets.OPS_API_CONSUMER_KEY }}
      OPS_API_CONSUMER_SECRET: ${{ secrets.OPS_API_CONSUMER_SECRET }}

    name: Python ${{ matrix.python-version }} on OS ${{ matrix.os }}
    steps:

    - name: Acquire sources
      uses: actions/checkout@v3

    - name: Install dependencies for Linux
      if: runner.os == 'Linux'
      run: |
        sudo apt install poppler-utils

    - name: Install dependencies for macOS
      if: runner.os == 'macOS'
      run: |
        brew install poppler

    - name: Setup Python
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
        architecture: x64
        cache: 'pip'
        cache-dependency-path: 'setup.py'

    - name: Setup project
      run: |
        pip install virtualenv
        make setup-test

    - name: Run tests
      run: make test-coverage options="--app-cache-backend=memory"

    - name: Upload coverage results to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        flags: unittests
        env_vars: OS,PYTHON
        name: codecov-umbrella
        fail_ci_if_error: false

  tests-ui:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [
          'ubuntu-latest',

          # Don't use macOS for now, it is currently unstable, otherwise slow. -- 2022-04-19, amo
          # 'macos-latest',
        ]
        node-version: ['11']

    defaults:
      run:
        shell: bash

    name: Node.js ${{ matrix.node-version }} on OS ${{ matrix.os }}
    steps:

    - name: Acquire sources
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        architecture: x64
        cache: 'yarn'
        cache-dependency-path: 'yarn.lock'

    - name: Setup project
      run: yarn install

    - name: Run build
      run: yarn build
